# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: CxrlosKenobi
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Santiago
          plugin_languages: yes
          plugin_languages_ignored: html, Jupyter notebook
          plugin_languages_skipped: Breakout-game
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: programming, markup, data
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: Retail-Pivot/app-backend, Retail-Pivot/app-frontend
          plugin_languages_analysis_timeout: 40
          plugin_languages_analysis_timeout_repositories: 15
          commits_authoring: Carlos, CxrlosKenobi, cxrlos@kenobi.dev, kenobi@ieee.org
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
